add fist section mobile
pasha-bulbuk/Adheart-test-template pull request #5
Opened 2023-05-31 17:35 UTC by misha-tarnavskyi

- close #1

2023-06-20 19:28 UTC, pasha-bulbuk requested changes
- [ ] в сайдбарі не повинно бути цього відступа
<img width="528" alt="Знімок екрана 2023-06-20 о 21 02 59" src="https://github.com/pasha-bulbuk/Adheart-test-template/assets/42435140/8e7b790b-bf0d-4a3c-a787-f0f4012bb70e">

- [ ] ці пункти мають бути у контейнері від якого мають робитись відступи як у випадку з основним контейнеро
<img width="380" alt="Знімок екрана 2023-06-20 о 21 03 10" src="https://github.com/pasha-bulbuk/Adheart-test-template/assets/42435140/2de6ed84-c1f8-41f2-b196-9028207be352">
<img width="414" alt="Знімок екрана 2023-06-20 о 21 03 17" src="https://github.com/pasha-bulbuk/Adheart-test-template/assets/42435140/8e25ab22-4176-4ff7-ab79-adbf7f818786">

- [ ] кнопка закриття сайдбару повинна бути такого ж розміру як і відкриття щоб хедер не пригав між цими станами

2023-06-20 19:28 UTC, pasha-bulbuk commented on index.html
> +                <div>Вход</div>
div блоки лишні всередині кнопок

2023-06-20 19:28 UTC, pasha-bulbuk commented on index.html
> +              <ul class="nav__list-bg">
класи всередині сайдбара не повинні відрізнятись від тих що в хедері, все залишається таким самим, міняється тільки ланцюжок звернень до них, взагалі блок burger__menu має мати клас sidebar і звернення відповідно мають бути .sidebar .nav__list

2023-06-20 19:28 UTC, pasha-bulbuk commented on css/style.css
> +}
давай притримуватись якоїсь структури, віднеси header__lang до стилів там де header вище

2023-06-20 19:30 UTC, misha-tarnavskyi commented on css/style.css
> +}
не поняв

2023-06-26 19:25 UTC, pasha-bulbuk requested changes
- [x] в сафарі воно виглядає ось так (селект вибору мови)
<img width="1624" alt="Знімок екрана 2023-06-26 о 20 29 45" src="https://github.com/pasha-bulbuk/Adheart-test-template/assets/42435140/6868b1cd-694a-4593-8d69-8c6e9e99de11">

- [ ] при розширенні 320 виглядає ось так, хоча не має, тому що ще досі є багато девайсів з таким розмірок екрану
<img width="413" alt="Знімок екрана 2023-06-26 о 20 31 05" src="https://github.com/pasha-bulbuk/Adheart-test-template/assets/42435140/9ee4c03b-d79c-4dcf-b45b-9933f1a20137">

- [ ] не так виглядає як має виглядати
<img width="160" alt="Знімок екрана 2023-06-26 о 20 33 27" src="https://github.com/pasha-bulbuk/Adheart-test-template/assets/42435140/360d9605-1611-42a9-b2bd-c66b7238e9ee">

- [ ] при наведенні на кнопки вони пригають, чого не має бути, подумай як це виправити, якщо не знайдеш рішення то я підскажу
- [ ] коли натискаєш на кнопку вход теж верстка пригає

2023-07-05 14:59 UTC, pasha-bulbuk requested changes
- [ ] так і не виправив момент коли все зміщається під час наведення
<img width="457" alt="Знімок екрана 2023-07-05 о 16 51 07" src="https://github.com/pasha-bulbuk/Adheart-test-template/assets/42435140/a5afadf2-c8e5-4272-8037-d570cc812d2e">

2023-07-11 17:21 UTC, pasha-bulbuk requested changes
не суттєво, але бачиш як виглядає навігаційний список, він не враховує всю висоту тега a, тому що це строковий тип тегу, а його потбріно зробити блочним додавши певний стиль, тоді все буде окей
<img width="881" alt="Знімок екрана 2023-07-11 о 19 14 54" src="https://github.com/pasha-bulbuk/Adheart-test-template/assets/42435140/e642ca13-bbd9-4b4f-814a-ea0d0fb58ac3">

<img width="887" alt="Знімок екрана 2023-07-11 о 19 14 50" src="https://github.com/pasha-bulbuk/Adheart-test-template/assets/42435140/fb1ed0e7-e57a-429b-9a1a-4e9d16a0870b">

2023-07-11 17:21 UTC, pasha-bulbuk commented on app.js
> +    document.querySelector("languague").classList.toggle("open2");
Не повинно бути класів open2 і тд, + не languague, а повинно бути language 
якщо ти хочеш додати унікальний клас open то використовуй модифікатор по бему, тобто language_open, тоді точно не буде проблем, або просто open але звертитись до цього класу потрібно буде через .language.open

2023-07-11 17:21 UTC, pasha-bulbuk commented on css/style.css
> +}
настав час оптимізувати цей файл, будемо використовувати препроцесор scss, почитай як його підключити, та потім перероби у відповідність з тим синтаксисом який він пропонує, зрозумієш в чому його перевага, але не одразу тут переробляй, а створи інший файл перенеси все в нього і тоді підключи та подивись чого не вистачає

2023-07-14 14:52 UTC, misha-tarnavskyi commented on css/style.css
> +}
Мені типо потрібно підключити scss та потім із css переробити в scss?

2023-08-04 17:45 UTC, pasha-bulbuk requested changes

2023-08-04 17:45 UTC, pasha-bulbuk commented on scss/main.scss
> +$color_9: black;
ніколи так не роби, а що ці кольори означають, як мені зрозуміти який колір додати елементу? 
я до прикладу хочу додати жовтий, як мені зрозуміти який з них жовтий?

2023-08-04 17:45 UTC, pasha-bulbuk commented on scss/main.scss
> +$color_1: rgba(21, 21, 31, 1);
Налаштуй у себе в середовищі дефолтні відступи (таби) в 2 пробіла

2023-08-04 17:45 UTC, pasha-bulbuk commented on scss/main.scss
> +}
перевага використання scss в тому щоб зменшити код і зробити більш зручним його читання та розуміння, для цього використовується вкладеність, по типу все що відноситься до хедеру, всі його блоки як от цей header__wrapper потрібно записувати всередині стилів хедера

```
.header {
	background-color: $background-color_1;
	height: 64px;
	
	&__wrapper {
	    display: flex;
	    align-items: center;
	    justify-content: space-between;
 	    height: 100%;
        }
}
```

2023-08-04 17:45 UTC, pasha-bulbuk commented on scss/main.scss
> +@media only screen and (min-width: 768px) {
також перевагою scss є те що можна написати міксин, який ти будеш використовувати для кожного класу окремо, як до прикладу ось цей медіа запит, дуже важко зрозуміти як поведе себе клас header__login на різних розмірах, тому що тут у нього поведінка одна, а вверху інша

тому тобі потрібно зробити так щоб можна було записувати ці медіа запити за допомогою міксину всередині основних стилів (блоку)

2023-08-22 11:32 UTC, pasha-bulbuk requested changes

2023-08-22 11:32 UTC, pasha-bulbuk commented on scss/main.scss
> +		}
ось ці псевдокласи записуй завжди внизу після головних стилей, тобто в даному випадку має бути ось так:

```
margin-left: 8px;
padding: 16px 24px;
border-radius: 38px;
background-color: $background-color_yellow;
font-family: $font-family_1;
font-weight: 600;
font-size: 1em;

&:hover {
	background: rgba(250, 226, 26, 1);
}
&:active {
	background: rgba(234, 203, 19, 1);
}
```

2023-08-22 11:32 UTC, pasha-bulbuk commented on scss/main.scss
> +  }
так, але у тебе може бути кілька уже готових рішень щоб не вказувати breakpoint, тобто можна зробити ось так:

```
@mixin tablet {
  @media (min-width: #{$breakpoints-tablet}) {
    @content;
  }
}

@mixin laptop {
  @media (min-width: #{$breakpoints-laptop}) {
    @content;
  }
}

@mixin desktop {
  @media (min-width: #{$breakpoints-desktop}) {
    @content;
  }
}
```

І можна також доповнювати іншими розмірами, до прикладу щось таке:

```
@mixin beforeDesktop {
  @media (max-width: #{$breakpoints-desktop - 1}) {
    @content;
  }
}

@mixin betweenTabletAndLaptop {
  @media only screen and (min-width: #{$breakpoints-tablet}) and (max-width: #{$breakpoints-laptop}) {
    @content;
  }
}
```

2023-08-22 11:32 UTC, pasha-bulbuk commented on scss/main.scss
> +$background-color_gray: #f1f1f1;
взагалі кольори виносять в змінні для того щоб можна було краще оперувати ними при зміні теми, записувати їх як змінні scss можна, але краще використовувати css змінні, погугли що це таке та як їх використовувати

також немає сенсу називати колір тим кольором яким він являється, бо на темній та світлій темі ці кольори можуть змінюватись

ось тут є хороша стаття на цю тему https://medium.com/@stefanmorris/proper-naming-of-color-variables-683264fec0f4

2023-08-22 11:32 UTC, pasha-bulbuk commented on scss/main.scss
> +.open {
ні, це не головний блок, це допоміжний клас, тобто всі класи які наслідуються нижче мають відноситись до nav, а не до open.

ти можеш зробити наступним чином, вказувати ось ці відмінності коли у nav буде класс open:

```
.nav {
  &.open &__item {}
  
  &.open &__link {}
  
  ...
}
```

2023-08-22 11:32 UTC, pasha-bulbuk commented on scss/main.scss
> +  }
І все це використовувати не в низу де ти відкриваєш медіа запрос і все в ньому пишеш, а тільки для якогось конкретного класа, до прикладу ось так:

```
.nav {
  &.open &__item {
    тут якісь стилі
    
    @include tablet {
      display: block;
      width: 100%;
    }
  }
  
  &.open &__link {}
  
  ...
}
```

2023-09-11 11:10 UTC, pasha-bulbuk approved these changes

2023-09-11 11:10 UTC, merged